### PR TITLE
yml first step

### PR DESCRIPTION
**Pull request by followynne**

### CODE REVIEW

**Comment by mo-esmp** [comment]
A quick note for authorize filter failed test, the cause for null expectation in `src/Serilog.Ui.Web/SerilogUiMiddleware.cs` and line
`var htmlStringBuilder = new StringBuilder(await new StreamReader(stream).ReadToEndAsync());` is the `index.html` file does not exist and the command `npm run build` is not executed.

**Comment by followynne** [comment]
@mo-esmp yep, thanks, you're right! I'll take the chance on this branch to also fix these tests 😊
I'll probably wait to pr-it until there's the new repo 😊

**Comment by mo-esmp** [comment]
A couple of days ago I requested to transfer the repo and waiting to be processed.

**Comment by followynne** [comment]
That's an awesome news, thanks for the update! 😊

**Comment by mo-esmp** [comment]
Nice job, all green checks!

**Comment by followynne** [comment]
Yes! Still need to tweak and fix the c# part though 😂

Maybe after that I'll give a try to Nuke as a Build tool 😊

**Pull request closed without merging**
